### ISSUE TITLE
SEW-related error

### ISSUE THREAD

**Issue by minhoha** [RALC88/gem5#3]
I inform you that there seems to be an error in reading the SEW value.
There seems to be an error in "VectorConfig::get_vtype_sew(uint64_t vtype)" function in "src/cpu/vector_engine/vpu/vector_config/vector_config.cc".
If SEW=32, vsew will output 4, if SEW=64, vsew will output 6. There seems to be a problem with shift, so I edit the value and it works normally. (vt(vtype,2,3) --> vt(vtype,3,3))

**Comment by RALC88** [comment]
Dear minhoha,
That configuration corresponds to the riscv-v-spec-0.7.1 ?
In page 7 of the spec there is a table (Table 2. vtype register layout) where :
6:5 vediv[1:0] Used by EDIV extension
4:2 vsew[2:0] Standard element width (SEW) setting
1:0 vlmul[1:0] Vector register group multiplier (LMUL) setting
Then for vsew is from bit 2  to bit 4 (3 bits).  This corresponds to vt(vtype,2,3) , which indicates that starts reading vtype in bit number 2 , and reads 3 bits.

In the case "if SEW=64, vsew will output 6", means that the switch case should enter to the default case and signal panic for all the apps which use 64-bits. But I have not seen that behavior. 

I will do a double check to be sure. Are you using the compiler for version 0.7 ??

**Comment by RALC88** [comment]
Dear minhoha,
That configuration corresponds to the riscv-v-spec-0.7.1 ?
In page 7 of the spec there is a table (Table 2. vtype register layout) where :
6:5 vediv[1:0] Used by EDIV extension
4:2 vsew[2:0] Standard element width (SEW) setting
1:0 vlmul[1:0] Vector register group multiplier (LMUL) setting
Then for vsew is from bit 2  to bit 4 (3 bits).  This corresponds to vt(vtype,2,3) , which indicates that starts reading vtype in bit number 2 , and reads 3 bits.

In the case "if SEW=64, vsew will output 6", means that the switch case should enter to the default case and signal panic for all the apps which use 64-bits. But I have not seen that behavior. 

I will do a double check to be sure. Are you using the compiler for version 0.7 ??

**Comment by RALC88** [comment]
Since there was no response, and I could not reproduce the error, the issue is closed.
